### ISSUE TITLE
Quality Assessment Checklist

### ISSUE THREAD

**Issue by mia-li-001** [404NameNotFound404/SolitaireSimulation#22]
**Team Culture:**
- [x] Build team culture through non-work activities - **Team dinner - picture in MarchMadness repo**
- [x] Regularly recognize and complement team members for their contributions - **Slack channel and comments on issues**
- [x] Respectfully provide coaching to improve team effectiveness and efficiency - **Comments on issues and during meetings**

**Communication:**
- [x] Set up and use communication tools and processes for effective and rapid information exchange - **Slack and zoom**
- [x] Use these tools and processes regularly - **Slack channel**
- [x] Establish and use remote communication tools and processes for distributed team interactions - **Slack**
- [x] Establish and use initiation and exit checklists - **In team documents repo**
- [x] Establish and use team policy statement - **In team documents repo**

**Testing:**
- [x] Design and execute tests for confirming refined user stories match initial user stories.
- [ ] Design and execute tests for confirming design matches refined user stories.
- [ ] Design and execute tests for confirming implementation matches design.
- [x] Create basic execution test capabilities.
- [ ] Create comprehensive test capabilities.
- [x] Create and regularly use unit testing - **See junit classes in test folder**
- [ ] Use a pull-request, code-review integration process for source changes.
- [ ] Automatically monitor and report code coverage.
- [ ] Use test-driven development.
- [ ] Measure and track software performance.

**Requirements and Analsys:**
- [x] Create user stories to capture basic product requirements - **Design Decisions document on OneDrive**
- [x] Analyze, refine, prioritize, select and convert user stories into tasks for development. - **Kanban board**
- [ ] Organize tasks into Epic-story-task packages.
- [ ] Experiment with Job Stories as an alternative to User Stories (see https://maherou.github.io/files/CS317/CS317-Links).

**Design:**
- [x] Create basic design documents such as class, interaction and use case - **Design document wiki**
- [ ] Write lightweight design documents
- [ ] Write throw-away prototype code to explore high-risk design elements.

**Development:**
- [x] Create GitHub Isses describing major design and development tasks - **Kanban board**
- [x] Establish GitHub Project (Kanban) board - **Kanban board**
- [x] Actively manage work by tracking issues on your Kanban board - **Kanban board**
- [x] Conduct regular project meetings to assess progress and manage schedule - **Zoom and slack channel**
- [ ] Use code formatting tool to assure uniform source code.
- [ ] Identify and use a coding convention.
- [x] Develop in-source comments that can be used to generate documentation, e.g., Javadoc or Doxygen - **Javadoc in source code**

**Product Release:**
- [ ] Create a unique and traceable release of your software product.
- [ ] Make a citable version (with DOI) of your code and make it available on Zenodo or Figshare.
- [ ] Generate user and developer documentation.
- [ ] Create product branding, e.g. logo family, catchphrase, product description.
